### ISSUE TITLE
Providing an sdist tarball on pypi

### ISSUE THREAD

**Issue by phmccarty** [matthewdeanmartin/termcolor#2]
Now that `yaspin` 2.2.0 depends on `termcolor-whl` instead of `termcolor`, Linux distributions that build packages from source will see the need to add a `termcolor-whl` package and use its sdist archive as input for the build.

Can the sdist tarball for `termcolor-whl` releases be made available on PyPI?

**Comment by matthewdeanmartin** [comment]
Issue addressed. Sorry it took so long.

https://pypi.org/project/termcolor-whl/#history

**Comment by phmccarty** [comment]
Thanks!
